version: '3'
services:
  app:
    container_name: colorimage-server
    restart: always
    build: .
    environment:
      POSTGRESQL_PROD_URL: elephantsql
      POSTGRESQL_DEV_URL: postgres://postgres:password@postgres:5432/colorimage
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: colorimage
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@colorimage.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  db-data:
  pgadmin-data: