FROM node:12-alpine AS builder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npx prisma generate
ARG DB_URL
ENV DATABASE_URL=${DB_URL}
RUN npx prisma db seed
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]