-- AlterTable
ALTER TABLE "Action" ADD COLUMN     "angle" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "selectedActionId" TEXT NOT NULL DEFAULT E'',
ADD COLUMN     "xScale" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN     "xTranslation" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "yScale" DOUBLE PRECISION DEFAULT 1,
ADD COLUMN     "yTranslation" DOUBLE PRECISION DEFAULT 0;
