DELETE FROM "Message";
DELETE FROM "ChannelMember";
DELETE FROM "Channel";
DELETE FROM "Stats";
DELETE FROM "Log";
DELETE FROM "Profile";
DELETE FROM "Account";
DELETE FROM "User";
DELETE FROM "Action";